import { createFileRoute, Link } from "@tanstack/react-router";
import { SiteHeader } from "@/components/SiteHeader";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
});

function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <SiteHeader />
      <main className="mx-auto max-w-3xl px-6 py-16">
        <Link
          to="/"
          className="mb-8 inline-block font-mono text-xs uppercase tracking-widest text-muted-foreground transition-colors hover:text-primary"
        >
          &larr; Back to home
        </Link>

        <h1 className="font-display text-5xl uppercase italic tracking-tighter">
          Terms &amp; Conditions
        </h1>
        <p className="mt-2 font-mono text-xs text-muted-foreground">
          Last updated: August 24, 2026
        </p>

        <div className="mt-10 space-y-8 font-mono text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using JEE Ranked, you agree to be bound by these Terms &amp;
              Conditions. If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              2. Description of Service
            </h2>
            <p>
              JEE Ranked is a competitive platform for practising JEE-level questions. You can play
              ranked 1v1 duels against other users where ELO ratings change based on results, or
              unranked sessions solo or against scheduled bot opponents — all on a shared timer. The
              service also provides leaderboards, player profiles, match replays and reviews, and
              AI-generated step-by-step explanations for questions.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              3. Eligibility &amp; Accounts
            </h2>
            <p>
              You must be at least 13 years old to create an account. You are responsible for
              maintaining the security of your account and credentials. You must provide accurate
              information when creating an account. One account per person — duplicate accounts may
              be suspended.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              4. Fair Play
            </h2>
            <p>
              You agree to play fairly. Using bots, scripts, browser extensions or any form of
              automation to answer questions is prohibited. Colluding with other players, creating
              multiple accounts, or otherwise manipulating ELO ratings is grounds for account
              suspension. Inactivity during an active match may result in automatic forfeiture. We
              reserve the right to investigate and take action against suspicious activity,
              including adjusting or resetting ratings affected by violations.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              5. ELO and Ranked Play
            </h2>
            <p>
              ELO ratings are calculated using a standard algorithm and are intended to reflect your
              skill level on the platform. Unranked matches do not affect your ELO. Ratings are
              provided as-is and we do not guarantee they accurately represent ability in any actual
              examination.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              6. Educational Content &amp; AI Explanations
            </h2>
            <p>
              Questions are provided for practice purposes and may be sourced from publicly
              available JEE preparation materials; we do not claim ownership of exam-level question
              content. Explanations may be generated by AI (Google's Gemini API) and can contain
              errors or incomplete reasoning — always verify solutions against official sources.
              Educational content is not affiliated with, endorsed by, or connected to NTA, IITs or
              any examination authority. Do not enter personal information into report details or
              profile fields beyond what is requested.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              7. User Conduct
            </h2>
            <p>
              The question report feature exists to flag incorrect or inappropriate content.
              Submitting false, abusive or spam reports is prohibited. Usernames, avatars and bios
              must not contain offensive, misleading or impersonating content. We may remove such
              content and suspend offending accounts.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              8. Intellectual Property
            </h2>
            <p>
              The JEE Ranked name, design, code and original content are owned by us. Questions
              remain the property of their respective sources. All third-party trademarks (including
              Google's) belong to their respective owners.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              9. Availability &amp; Termination
            </h2>
            <p>
              We do not guarantee uninterrupted availability of the service. We reserve the right to
              suspend or terminate your account at our discretion, particularly in cases of fair
              play violations, automated play, or abusive behaviour. You may delete your account at
              any time by contacting us.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              10. Disclaimer &amp; Limitation of Liability
            </h2>
            <p>
              JEE Ranked is provided "as is" without warranties of any kind. To the maximum extent
              permitted by law, we are not liable for any direct or indirect damages arising from
              your use of the service, including reliance on educational content or AI-generated
              explanations. Use at your own risk.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              11. Changes to Terms
            </h2>
            <p>
              We may modify these Terms at any time. Continued use of the service after changes
              constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              12. Governing Law
            </h2>
            <p>These Terms are governed by the laws of India.</p>
          </section>

          <section>
            <h2 className="mb-3 font-mono text-xs font-bold uppercase tracking-widest text-foreground">
              13. Contact
            </h2>
            <p>
              For questions about these Terms, email{" "}
              <a
                href="mailto:info@jeeranked.com"
                className="text-primary transition-colors hover:text-foreground"
              >
                info@jeeranked.com
              </a>{" "}
              or reach us on Instagram (@jeeranked) or YouTube (@jeeranked).
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
